Repository cryptoeconomicslab/gazelle, pull requests merged in 2019-11, with the labels that each got.

#28 [Impl] Write Decision data structure of OVM #19
  __tests__/db/KeyValueStore.test.ts
  __tests__/db/RangeDb.test.ts
  __tests__/events/EventDb.test.ts
  __tests__/ovm/NotDecider.test.ts
  __tests__/wallet/EthWallet.test.ts
  src/contract/eth/CommitmentContract.ts
  src/contract/interfaces/ICommitmentContract.ts
  src/db/InMemoryKeyValueStore.ts
  src/db/KeyValueStore.ts
  src/db/RangeDb.ts
  src/db/RangeStore.ts
  src/db/WitnessStore.ts
  src/decider/Decider.ts
  src/decider/deciderManager.ts
  src/decider/sampleDecider.ts
  src/events/EventDb.ts
  src/events/eth/EventWatcher.ts
  src/ovm/DeciderManager.ts
  src/ovm/deciders/atomic/SampleDecider.ts
  src/ovm/deciders/index.ts
  src/ovm/deciders/operators/NotDecider.ts
  src/ovm/interfaces/Decider.ts
  src/ovm/types.ts
  src/types/Codables/Bytes.ts
  src/types/types.ts
  src/wallet/eth/EthWallet.ts
  src/wallet/interfaces/IWallet.ts
Labels: OVM

#42 change the interface of EthCoder and fix Bytes.fromHexString
  __tests__/coder/Bytes.test.ts
  __tests__/coder/EthCoder.test.ts
  __tests__/ovm/AndDecider.test.ts
  __tests__/ovm/NotDecider.test.ts
  src/coder/Coder.ts
  src/coder/EthCoder.ts
  src/ovm/deciders/operators/AndDecider.ts
  src/ovm/deciders/operators/NotDecider.ts
  src/types/Codables/Bytes.ts
Labels: bug, enhancement

#50 deposit contract wrapper
  __tests__/wallet/EthWallet.test.ts
  src/contract/eth/CommitmentContract.ts
  src/contract/eth/DepositContract.ts
  src/contract/index.ts
  src/contract/interfaces/IDepositContract.ts
  src/wallet/eth/EthWallet.ts
  src/wallet/eth/EthWalletFactory.ts
  src/wallet/interfaces/IWallet.ts
Labels: L1 agnostic

#85 feat add open to kvs interface
  src/db/InMemoryKeyValueStore.ts
  src/db/IndexedDbKeyValueStore.ts
  src/db/KeyValueStore.ts
Labels: Database, enhancement
